raw_columns:
  - ticker
  - per
  - date
  - time
  - open
  - high
  - low
  - close
  - vol
  - openint

validated_columns:
  - date
  - raw_ticker
  - ticker
  - open
  - high
  - low
  - close
  - volume
  - openint
  - source_file
  - year
